SELECT STR.STR_COD, 
       STR.STR_NOME,
       BNC.BNC_COD,
       BNC.BNC_NOME,
       SMK.SMK_COD, 
       SMK.SMK_ROT,
       COUNT(*) QTD,
       ROUND(AVG(SMM.SMM_VLR), 2) VALOR
FROM OSM 
     INNER JOIN SMM ON (OSM.OSM_SERIE =  SMM.SMM_OSM_SERIE) AND (OSM.OSM_NUM = SMM.SMM_OSM)
     INNER JOIN SMK ON (SMM.SMM_COD = SMK.SMK_COD) AND (SMM.SMM_TPCOD = SMK.SMK_TIPO)
     INNER JOIN STR ON (OSM.OSM_STR = STR.STR_COD)
     INNER JOIN RCL ON (OSM.OSM_SERIE = RCL.RCL_OSM_SERIE) AND (OSM.OSM_NUM = RCL.RCL_OSM) AND (SMM.SMM_COD = RCL.RCL_COD) AND (SMM.SMM_TPCOD = RCL.RCL_TPCOD)
     LEFT JOIN FTE ON  (RCL.RCL_FTE_SERIE = FTE.FTE_SERIE) AND (RCL.RCL_FTE_NUM = FTE.FTE_NUM) AND (SMM.SMM_STR = FTE.FTE_STR_COD)
     LEFT JOIN BNC ON  (FTE.FTE_BNC_COD = BNC.BNC_COD)

WHERE RCL.RCL_FTE_SERIE IS NOT NULL AND
      OSM.OSM_DTHR >=  '2024-09-01 00:00:00'  AND 
      OSM.OSM_DTHR <=  '2024-09-05 00:00:00' 
 
GROUP BY BNC.BNC_COD,
         BNC.BNC_NOME,
         STR.STR_COD, 
         STR.STR_NOME,
         SMK.SMK_COD,
         SMK.SMK_ROT

UNION ALL

SELECT STR.STR_COD, 
       STR.STR_NOME,
       BNC.BNC_COD,
       BNC.BNC_NOME,
       SMK.SMK_COD, 
       SMK.SMK_ROT,
       COUNT(*) QTD,
       ROUND(AVG(SMM.SMM_VLR), 2) VALOR
FROM OSM 
     INNER JOIN SMM ON (OSM.OSM_SERIE =  SMM.SMM_OSM_SERIE) AND (OSM.OSM_NUM = SMM.SMM_OSM)
     INNER JOIN SMK ON (SMM.SMM_COD = SMK.SMK_COD) AND (SMM.SMM_TPCOD = SMK.SMK_TIPO)
     INNER JOIN STR ON (OSM.OSM_STR = STR.STR_COD)
     INNER JOIN RCL ON (OSM.OSM_SERIE = RCL.RCL_OSM_SERIE) AND (OSM.OSM_NUM = RCL.RCL_OSM) AND (SMM.SMM_COD = RCL.RCL_COD) AND (SMM.SMM_TPCOD = RCL.RCL_TPCOD)
     LEFT JOIN SBN ON  (SMM.SMM_STR = SBN.SBN_STR_COD) AND (SMK.SMK_COD = SBN.SBN_SMK_COD) AND (SMK.SMK_TIPO = SBN.SBN_CTF_TIPO)       
     LEFT JOIN BNC ON (SBN.SBN_BNC_COD = BNC.BNC_COD) 

WHERE RCL.RCL_FTE_SERIE IS NULL AND
      OSM.OSM_DTHR >=  '2024-09-01 00:00:00'  AND 
      OSM.OSM_DTHR <=  '2024-09-05 00:00:00' 
 
GROUP BY BNC.BNC_COD,
         BNC.BNC_NOME,
         STR.STR_COD, 
         STR.STR_NOME,
         SMK.SMK_COD,
         SMK.SMK_ROT

ORDER BY STR.STR_NOME ASC,
         BNC.BNC_NOME ASC,
         SMK.SMK_ROT ASC