SELECT 
    CNV.CNV_COD COD_CONVENIO,
    CNV.CNV_NOME NOME_CONVENIO,
    PAC.PAC_REG REGISTRO,
    PAC.PAC_NOME PACIENTE,
    OSM.OSM_SERIE OS_SERIE,
    OSM.OSM_NUM OS_NUM,
    SUM(SMM.SMM_VLR) OS_VALOR,
    CONVERT(VARCHAR, OSM.OSM_DTHR, 103) OS_DATA,
    FAT.FAT_SERIE,
    FAT.FAT_NUM,
    MOG.MOG_NOME PENDENTE
FROM
    OSM
    INNER JOIN PAC ON (OSM.OSM_PAC = PAC.PAC_REG)
    INNER JOIN CNV ON (OSM.OSM_CNV = CNV.CNV_COD)
    INNER JOIN SMM ON (OSM.OSM_SERIE = SMM.SMM_OSM_SERIE) AND (OSM.OSM_NUM = SMM.SMM_OSM)
    LEFT JOIN FAT ON (SMM.SMM_FAT = FAT.FAT_NUM) AND (SMM.SMM_FAT_SERIE = FAT.FAT_SERIE) 
    LEFT JOIN NFS ON (FAT.FAT_NFS_SERIE = NFS.NFS_SERIE) AND (FAT.FAT_NFS_NUMERO = NFS.NFS_NUMERO) AND (FAT.FAT_NFS_TIPO = NFS.NFS_TIPO) 
    LEFT JOIN GLF ON (GLF.GLF_OSM_SERIE = OSM.OSM_SERIE) AND (GLF.GLF_OSM_NUM = OSM.OSM_NUM) AND (GLF.GLF_DTHR_SOL IS NULL)
    LEFT JOIN MOG ON (GLF.GLF_MOG_COD = MOG.MOG_COD)
 
WHERE 
    OSM.OSM_DTHR >=  :DATA_INICIO  AND
    OSM.OSM_DTHR <=  :DAT_FIM  AND
    CNV.CNV_CAIXA_FATURA = 'F' AND
    SMM.SMM_TIPO_FATURA = 'E' AND
    SMM.SMM_EXEC <> 'C' AND
    SMM.SMM_SFAT <> 'C' AND CNV.CNV_COD = 'SUL' AND
    SMM.SMM_PACOTE IN (NULL, 'P') AND
    NFS.NFS_NUMERO IS NULL
GROUP BY 
    CNV.CNV_COD,
    CNV.CNV_NOME,
    PAC.PAC_REG,
    PAC.PAC_NOME,
    OSM.OSM_SERIE,
    OSM.OSM_NUM, 
    OSM.OSM_DTHR,
    FAT.FAT_SERIE,
    FAT.FAT_NUM, 
    MOG.MOG_NOME

HAVING SUM(SMM.SMM_VLR) > 0

ORDER BY 
    CNV.CNV_NOME ASC,
    OSM.OSM_DTHR ASC
