SELECT ESP.ESP_NOME AS ESPECIALIDADE,
       COUNT(SMM.SMM_COD) AS QTD,
       SUM(SMM.SMM_VLR) AS FATURAMENTO,
       RIGHT('0' + CONVERT(VARCHAR, DATEPART(MM, OSM.OSM_DTHR)), 2) +'/'+ CONVERT(VARCHAR, DATEPART(YYYY, OSM.OSM_DTHR)) AS COMPETENCIA
       

FROM OSM
     INNER JOIN SMM ON (OSM.OSM_SERIE = SMM.SMM_OSM_SERIE) AND (OSM.OSM_NUM = SMM.SMM_OSM)
     INNER JOIN SMK ON (SMM.SMM_COD = SMK.SMK_COD) AND (SMM.SMM_TPCOD = SMK.SMK_TIPO)
     LEFT JOIN ESP ON (SMK.SMK_ESP_COD = ESP.ESP_COD)

WHERE OSM.OSM_DTHR >=  :DATA_INICIO AND --Filtro de data para trazer apenas um recorte
      OSM.OSM_DTHR <=  :DATA_FIM AND
      SMM.SMM_TIPO_FATURA = 'E' AND
      SMM.SMM_EXEC <> 'C'  AND
      SMM.SMM_SFAT <> 'C' AND 
      SMM.SMM_PACOTE IN (NULL, 'P') 

GROUP BY ESP.ESP_NOME, DATEPART(YYYY, OSM.OSM_DTHR), DATEPART(MM, OSM.OSM_DTHR)
HAVING (SUM(SMM.SMM_VLR))>0
ORDER BY ESP.ESP_NOME ASC, DATEPART(YYYY, OSM.OSM_DTHR) ASC, DATEPART(MM, OSM.OSM_DTHR) ASC
