SELECT * FROM (
WITH LINTERN AS (
   SELECT HSP.HSP_NUM, 
          HSP.HSP_DTHRE,
          HSP.HSP_TRAT_INT
   FROM HSP 
   WHERE HSP.hsp_dthre >= :DATA_INICIAL AND
			HSP.hsp_dthre <= :DATA_INICIAL + INTERVAL '24' HOUR AND
         HSP.HSP_PAC = :REGISTRO
   ORDER BY HSP.HSP_NUM DESC
),
TOPTWO AS (
   SELECT HSP_NUM
   FROM (SELECT HSP_NUM, ROWNUM AS RN
         FROM LINTERN)
   WHERE RN <= 2
),
ADMTRAT AS(
   SELECT HSP_DTHRE
   FROM (SELECT HSP_DTHRE, 
                HSP_NUM, 
                HSP_TRAT_INT,
                ROWNUM AS RN
         FROM LINTERN
         WHERE HSP_TRAT_INT = 'T')
   WHERE RN <= 1 
)

SELECT PAC.PAC_REG,
       PAC.PAC_NOME,
       'Magnésio Sérico' as EXAME,
       SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30156, 01)/1000 AS RESULTADO,
       RCL.RCL_DTHR
FROM RCL 
     INNER JOIN PAC ON (RCL.RCL_PAC = PAC.PAC_REG)
WHERE RCL.RCL_COD IN ('3858') ANDRCL.RCL_PAC = :REGISTRO AND
      RCL.RCL_HSP IN (SELECT HSP_NUM FROM TOPTWO) AND 
      RCL.RCL_DTHR <= (SELECT HSP_DTHRE + INTERVAL '48' HOUR FROM ADMTRAT) AND
SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30156, 01) <> '?'

UNION ALL

SELECT PAC.PAC_REG,
       PAC.PAC_NOME,
       'Sódio Sérico' as EXAME,
       SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30163, 01)/1000 AS RESULTADO,
       RCL.RCL_DTHR
FROM RCL 
     INNER JOIN PAC ON (RCL.RCL_PAC = PAC.PAC_REG)
WHERE RCL.RCL_COD IN ('3873') ANDRCL.RCL_PAC = :REGISTRO AND
      RCL.RCL_HSP IN (SELECT HSP_NUM FROM TOPTWO) AND 
      RCL.RCL_DTHR <= (SELECT HSP_DTHRE + INTERVAL '48' HOUR FROM ADMTRAT) AND
SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30163, 01) <> '?'

UNION ALL

SELECT PAC.PAC_REG,
       PAC.PAC_NOME,
       'Potássio Sérico' as EXAME,
       SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30159, 01)/1000 AS RESULTADO,
       RCL.RCL_DTHR
FROM RCL 
     INNER JOIN PAC ON (RCL.RCL_PAC = PAC.PAC_REG)
WHERE RCL.RCL_COD IN ('3867') AND
RCL.RCL_DTHR >=  to_date ( '2024-09-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss' ) AND
RCL.RCL_DTHR <=  to_date ( '2024-09-10 00:00:00', 'yyyy-mm-dd hh24:mi:ss' )  AND
SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30159, 01) <> '?'

UNION ALL

SELECT PAC.PAC_REG,
       PAC.PAC_NOME,
       'Creatinina Sérico' as EXAME,
       SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30145, 01)/1000 AS RESULTADO,
       RCL.RCL_DTHR
FROM RCL 
     INNER JOIN PAC ON (RCL.RCL_PAC = PAC.PAC_REG)
WHERE RCL.RCL_COD IN ('3801') AND
RCL.RCL_DTHR >=  to_date ( '2024-09-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss' ) AND
RCL.RCL_DTHR <=  to_date ( '2024-09-10 00:00:00', 'yyyy-mm-dd hh24:mi:ss' )  AND
SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30145, 01) <> '?'

UNION ALL

SELECT PAC.PAC_REG,
       PAC.PAC_NOME,
       'Ureia Sérico' as EXAME,
       SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30112, 01)/1000 AS RESULTADO,
       RCL.RCL_DTHR
FROM RCL 
     INNER JOIN PAC ON (RCL.RCL_PAC = PAC.PAC_REG)
WHERE RCL.RCL_COD IN ('3888') AND
RCL.RCL_DTHR >=  to_date ( '2024-09-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss' ) AND
RCL.RCL_DTHR <=  to_date ( '2024-09-10 00:00:00', 'yyyy-mm-dd hh24:mi:ss' )  AND
SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30112, 01) <> '?'

UNION ALL

SELECT PAC.PAC_REG,
       PAC.PAC_NOME,
       'Ureia Sérico' as EXAME,
       SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30112, 01)/1000 AS RESULTADO,
       RCL.RCL_DTHR
FROM RCL 
     INNER JOIN PAC ON (RCL.RCL_PAC = PAC.PAC_REG)
WHERE RCL.RCL_COD IN ('3888') AND
RCL.RCL_DTHR >=  to_date ( '2024-09-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss' ) AND
RCL.RCL_DTHR <=  to_date ( '2024-09-10 00:00:00', 'yyyy-mm-dd hh24:mi:ss' )  AND
SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30112, 01) <> '?'

UNION ALL 

SELECT PAC.PAC_REG,
       PAC.PAC_NOME,
       'NT-próBNP' as EXAME,
       SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 45525, 01)/1000 AS RESULTADO,
       RCL.RCL_DTHR
FROM RCL 
     INNER JOIN PAC ON (RCL.RCL_PAC = PAC.PAC_REG)
WHERE RCL.RCL_COD IN ('88021158') ANDRCL.RCL_PAC = :REGISTRO AND
      RCL.RCL_HSP IN (SELECT HSP_NUM FROM TOPTWO) AND 
      RCL.RCL_DTHR <= (SELECT HSP_DTHRE + INTERVAL '48' HOUR FROM ADMTRAT) AND
SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 45525, 01) <> '?'

UNION ALL 

SELECT PAC.PAC_REG,
       PAC.PAC_NOME,
       'Plaquetas' as EXAME,
       SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30212, 01)/1000 AS RESULTADO,
       RCL.RCL_DTHR
FROM RCL 
     INNER JOIN PAC ON (RCL.RCL_PAC = PAC.PAC_REG)
WHERE RCL.RCL_COD IN ('3697') ANDRCL.RCL_PAC = :REGISTRO AND
      RCL.RCL_HSP IN (SELECT HSP_NUM FROM TOPTWO) AND 
      RCL.RCL_DTHR <= (SELECT HSP_DTHRE + INTERVAL '48' HOUR FROM ADMTRAT) AND
SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30212, 01) <> '?'


UNION ALL 

SELECT PAC.PAC_REG,
       PAC.PAC_NOME,
       'Plaquetas' as EXAME,
       SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30212, 01)/1000 AS RESULTADO,
       RCL.RCL_DTHR
FROM RCL 
     INNER JOIN PAC ON (RCL.RCL_PAC = PAC.PAC_REG)
WHERE RCL.RCL_COD IN ('3697') ANDRCL.RCL_PAC = :REGISTRO AND
      RCL.RCL_HSP IN (SELECT HSP_NUM FROM TOPTWO) AND 
      RCL.RCL_DTHR <= (SELECT HSP_DTHRE + INTERVAL '48' HOUR FROM ADMTRAT) AND
SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30212, 01) <> '?' 

UNION ALL 

SELECT PAC.PAC_REG,
       PAC.PAC_NOME,
       'Linfócitos' as EXAME,
       SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30007, 01)/1000 AS RESULTADO,
       RCL.RCL_DTHR
FROM RCL 
     INNER JOIN PAC ON (RCL.RCL_PAC = PAC.PAC_REG)
WHERE RCL.RCL_COD IN ('3697') ANDRCL.RCL_PAC = :REGISTRO AND
      RCL.RCL_HSP IN (SELECT HSP_NUM FROM TOPTWO) AND 
      RCL.RCL_DTHR <= (SELECT HSP_DTHRE + INTERVAL '48' HOUR FROM ADMTRAT) AND
SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30007, 01) <> '?' 

UNION ALL 

SELECT PAC.PAC_REG,
       PAC.PAC_NOME,
       'Contagem Global' as EXAME,
       SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30007, 01)/1000 AS RESULTADO,
       RCL.RCL_DTHR
FROM RCL 
     INNER JOIN PAC ON (RCL.RCL_PAC = PAC.PAC_REG)
WHERE RCL.RCL_COD IN ('3697') ANDRCL.RCL_PAC = :REGISTRO AND
      RCL.RCL_HSP IN (SELECT HSP_NUM FROM TOPTWO) AND 
      RCL.RCL_DTHR <= (SELECT HSP_DTHRE + INTERVAL '48' HOUR FROM ADMTRAT) AND
SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30007, 01) <> '?' 

UNION ALL

SELECT PAC.PAC_REG,
       PAC.PAC_NOME,
       'Hematócrito' as EXAME,
       SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30005, 02)/1000 AS RESULTADO,
       RCL.RCL_DTHR
FROM RCL 
     INNER JOIN PAC ON (RCL.RCL_PAC = PAC.PAC_REG)
WHERE RCL.RCL_COD IN ('3697') ANDRCL.RCL_PAC = :REGISTRO AND
      RCL.RCL_HSP IN (SELECT HSP_NUM FROM TOPTWO) AND 
      RCL.RCL_DTHR <= (SELECT HSP_DTHRE + INTERVAL '48' HOUR FROM ADMTRAT) AND
SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30005, 02) <> '?' 

UNION ALL

SELECT PAC.PAC_REG,
       PAC.PAC_NOME,
       'Hemoglobina' as EXAME,
       SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30005, 01)/1000 AS RESULTADO,
       RCL.RCL_DTHR
FROM RCL 
     INNER JOIN PAC ON (RCL.RCL_PAC = PAC.PAC_REG)
WHERE RCL.RCL_COD IN ('3697') ANDRCL.RCL_PAC = :REGISTRO AND
      RCL.RCL_HSP IN (SELECT HSP_NUM FROM TOPTWO) AND 
      RCL.RCL_DTHR <= (SELECT HSP_DTHRE + INTERVAL '48' HOUR FROM ADMTRAT) AND
SMART.F_RESULTADO_RCL_2(RCL.RCL_TXT, 30005, 01) <> '?' 

)X