SELECT PAC.PAC_REG, 
       PAC.PAC_NOME,
       CAST(PAC.PAC_NASC AS DATE) NASCIMENTO,
       PSV.PSV_APEL,
       LOC.LOC_NOME,
       HSP.HSP_DTHRE,
       RCL.RCL_DTHR
FROM RCL 
     INNER JOIN PAC ON (RCL.RCL_PAC =  PAC.PAC_REG)
     INNER JOIN PSV ON (RCL.RCL_MED = PSV.PSV_COD)
     INNER JOIN HSP ON (RCL.RCL_PAC = HSP.HSP_PAC) AND (RCL.RCL_HSP = HSP.HSP_NUM)
     INNER JOIN LOC ON (HSP.HSP_LOC = LOC.LOC_COD)
WHERE RCL.RCL_DTHR >  to_date ( '2024-11-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss' ) AND
      RCL.RCL_DTHR <  to_date ( '2024-11-02 00:00:00', 'yyyy-mm-dd hh24:mi:ss' ) 