SELECT 'PACOTE' AS TIPO,
       SMK.SMK_COD,
       SMK.SMK_ROT,
       SUM (SMM.SMM_QT),
       ((SUM (SMM.SMM_VLR)) / (SUM (SMM.SMM_QT))) AS RECEITA_UNI,
       SUM (SMM.SMM_VLR) AS RECEITA_TOT,
       SUM(DRE.DRE_MAT_VLR) AS MAT_TOT

FROM SMM
     INNER JOIN SMK ON (SMM.SMM_COD = SMK.SMK_COD) AND (SMM.SMM_TPCOD = SMK.SMK_TIPO)
     INNER JOIN DRE ON (SMM.SMM_OSM_SERIE = DRE.DRE_OSM_SERIE) AND (SMM.SMM_OSM = DRE.DRE_OSM)

WHERE SMM.SMM_DTHR_EXEC >= '2024-05-01 00:00:00' AND 
      SMM.SMM_DTHR_EXEC <= '2024-05-31 23:59:59' AND 
      SMK.SMK_TIPO='S' AND 
      SMM.SMM_PACOTE IS NOT NULL

GROUP BY SMK.SMK_COD,
         SMK.SMK_ROT