SELECT CNV.CNV_NOME,
       RIGHT('0' + CONVERT(VARCHAR, DATEPART(MM, OSM.OSM_DTHR)), 2) +'/'+ CONVERT(VARCHAR, DATEPART(YYYY, OSM.OSM_DTHR)) AS COMPETENCIA,
       SUM(SMM.SMM_VLR) AS FATURAMENTO,
       SUM(CASE WHEN SMM.SMM_TPCOD = 'M' THEN SMM.SMM_VLR ELSE 0 END) AS MATMED,
       SUM(CASE WHEN SMM.SMM_TPCOD = 'M' AND ABAPREC.PRE_SMK_COD IS NOT NULL AND ABAPREC.PRE_PORT = 'S' THEN SMM.SMM_VLR ELSE 0 END) AS LISTA_POSITIVA,
       SUM(CASE WHEN SMM.SMM_TPCOD = 'M' AND ABAPREC.PRE_SMK_COD IS NOT NULL AND ABAPREC.PRE_PORT = 'S' THEN SMK.SMK_PRECO_CUSTO  ELSE 0 END) AS PRECO_CUSTO
       

FROM OSM
     INNER JOIN CNV ON (OSM.OSM_CNV = CNV.CNV_COD)
     INNER JOIN SMM ON (OSM.OSM_SERIE = SMM.SMM_OSM_SERIE) AND (OSM.OSM_NUM = SMM.SMM_OSM)
     INNER JOIN SMK ON (SMM.SMM_COD = SMK.SMK_COD) AND (SMM.SMM_TPCOD = SMK.SMK_TIPO)
     LEFT JOIN ABAPREC ON (ABAPREC.PRE_SMK_COD = SMM.SMM_COD) AND (ABAPREC.PRE_SMK_TIPO = SMK.SMK_TIPO)

WHERE OSM.OSM_DTHR >=   '2025-01-01 00:00:00'  AND 
      OSM.OSM_DTHR <=   '2025-01-31 23:59:59'  AND
      SMM.SMM_TIPO_FATURA = 'E' AND
      SMM.SMM_EXEC <> 'C'  AND
      SMM.SMM_SFAT <> 'C' AND 
      SMM.SMM_PACOTE IN (NULL, 'P') 

GROUP BY CNV.CNV_NOME, DATEPART(YYYY, OSM.OSM_DTHR), DATEPART(MM, OSM.OSM_DTHR)
HAVING (SUM(SMM.SMM_VLR))>0
ORDER BY CNV.CNV_NOME ASC, DATEPART(YYYY, OSM.OSM_DTHR) ASC, DATEPART(MM, OSM.OSM_DTHR) ASC