SELECT 
      TIPO_MEDICO, 
      CNS,
      NOME_CIRURGIAO,
      NOME_PACIENTE,
      REGISTRO,
      SERIE_OS,
      NUM_OS,
      DT_ATENDIMENTO,
      CONVENIO,
      ITEM,
      TABELA_SIGTAP, 
      CASE
          WHEN RN = 1 AND TIPO_MEDICO = 'CIRURGIÃO' THEN (TABELA_SIGTAP * 40) / 100
          WHEN RN = 2 AND TIPO_MEDICO = 'CIRURGIÃO' THEN (TABELA_SIGTAP * 75 / 100) * 40 / 100
          WHEN RN >= 3 AND TIPO_MEDICO = 'CIRURGIÃO' THEN (TABELA_SIGTAP * 50 / 100) * 40 / 100
      ELSE 0          
      END AS VALOR_REPASSE_CIRUGIAO,
      
      CASE 
          WHEN RN = 1 AND TIPO_MEDICO = 'ANESTESISTA' THEN (TABELA_SIGTAP * 10 / 100)
          WHEN RN = 2 AND TIPO_MEDICO = 'ANESTESISTA' THEN (TABELA_SIGTAP * 10 / 100) * 40 / 100
          WHEN RN >= 3 AND TIPO_MEDICO = 'ANESTESISTA' THEN (TABELA_SIGTAP * 50 / 100) * 10 / 100
      ELSE 0
      END AS VALOR_REPASSE_ANEST
FROM(
SELECT RANK() OVER (PARTITION BY RCI.RCI_OSM_NUM ORDER BY RCI.RCI_NUM ASC) AS RN,
        CASE
              WHEN ECI.ECI_FUNCAO = 'A'
              THEN 'ANESTESISTA'
          ELSE 'CIRURGIÃO' END AS TIPO_MEDICO,
      PSV.PSV_CARTAO_SUS AS CNS,
      PSV.PSV_APEL AS NOME_CIRURGIAO,
      PAC.PAC_NOME AS NOME_PACIENTE,
      PAC.PAC_REG AS REGISTRO,
      RCI.RCI_OSM_SERIE AS SERIE_OS,
      RCI.RCI_OSM_NUM AS NUM_OS,
      RCI.RCI_DTHR_INI AS DT_ATENDIMENTO,
      CNV.CNV_COD AS CONVENIO,
      SMK.SMK_ROT AS ITEM,
      CASE WHEN CLE.CLE_PADRAO_PRECO = 1 THEN PRE.PRE_VLR_P1
           WHEN CLE.CLE_PADRAO_PRECO = 2 THEN PRE.PRE_VLR_P2
           WHEN CLE.CLE_PADRAO_PRECO = 3 THEN PRE.PRE_VLR_P3
           WHEN CLE.CLE_PADRAO_PRECO = 4 THEN PRE.PRE_VLR_P4
           WHEN CLE.CLE_PADRAO_PRECO = 5 THEN PRE.PRE_VLR_P5
       END AS TABELA_SIGTAP

FROM RCI
     INNER JOIN ECI ON (ECI.ECI_RCI_SERIE = RCI.RCI_SERIE) AND (ECI.ECI_RCI_NUM = RCI.RCI_NUM)
     INNER JOIN PSV ON (ECI.ECI_FUNCAO = 'C') AND (ECI.ECI_PSV_COD = PSV.PSV_COD) AND (ECI.ECI_PSV_COD <> '123')
     INNER JOIN PAC ON (RCI.RCI_PAC_REG = PAC.PAC_REG)
     INNER JOIN CNV ON (RCI.RCI_CNV_COD = CNV.CNV_COD)
     INNER JOIN SMK ON (RCI.RCI_SMK_COD = SMK.SMK_COD) AND (RCI.RCI_SMK_TIPO = SMK.SMK_TIPO) 
     INNER JOIN LOC ON (RCI.RCI_LOC_COD = LOC.LOC_COD)
     INNER JOIN CLE ON (LOC.LOC_CLE_COD = CLE.CLE_COD)
     LEFT JOIN PRE ON (SMK.SMK_TIPO = PRE.PRE_SMK_TIPO) AND (SMK.SMK_COD = PRE.PRE_SMK_COD) AND (PRE.PRE_TAB_COD = 'SUS')
   
WHERE RCI_OSM_SERIE=125 AND  
      RCI_OSM_NUM IN (7409,11420) AND
      RCI_SMK_COD <> '04150200'

UNION ALL

SELECT RANK() OVER (PARTITION BY RCI.RCI_OSM_NUM ORDER BY RCI.RCI_NUM ASC) AS RN,
        CASE
              WHEN ECI.ECI_FUNCAO = 'A'
              THEN 'ANESTESISTA'
          ELSE 'CIRURGIÃO' END AS TIPO_MEDICO,
      PSV.PSV_CARTAO_SUS AS CNS,
      PSV.PSV_APEL AS NOME_CIRURGIAO,
      PAC.PAC_NOME AS NOME_PACIENTE,
      PAC.PAC_REG AS REGISTRO,
      RCI.RCI_OSM_SERIE AS SERIE_OS,
      RCI.RCI_OSM_NUM AS NUM_OS,
      RCI.RCI_DTHR_INI AS DT_ATENDIMENTO,
      CNV.CNV_COD AS CONVENIO,
      SMK.SMK_ROT AS ITEM,
      CASE WHEN CLE.CLE_PADRAO_PRECO = 1 THEN PRE.PRE_VLR_P1
           WHEN CLE.CLE_PADRAO_PRECO = 2 THEN PRE.PRE_VLR_P2
           WHEN CLE.CLE_PADRAO_PRECO = 3 THEN PRE.PRE_VLR_P3
           WHEN CLE.CLE_PADRAO_PRECO = 4 THEN PRE.PRE_VLR_P4
           WHEN CLE.CLE_PADRAO_PRECO = 5 THEN PRE.PRE_VLR_P5
       END AS TABELA_SIGTAP

FROM RCI
     INNER JOIN ECI ON (ECI.ECI_RCI_SERIE = RCI.RCI_SERIE) AND (ECI.ECI_RCI_NUM = RCI.RCI_NUM)
     INNER JOIN PSV ON (ECI.ECI_FUNCAO = 'A') AND (ECI.ECI_PSV_COD = PSV.PSV_COD) AND (ECI.ECI_PSV_COD <> '123')
     INNER JOIN PAC ON (RCI.RCI_PAC_REG = PAC.PAC_REG)
     INNER JOIN CNV ON (RCI.RCI_CNV_COD = CNV.CNV_COD)
     INNER JOIN SMK ON (RCI.RCI_SMK_COD = SMK.SMK_COD) AND (RCI.RCI_SMK_TIPO = SMK.SMK_TIPO) 
     INNER JOIN LOC ON (RCI.RCI_LOC_COD = LOC.LOC_COD)
     INNER JOIN CLE ON (LOC.LOC_CLE_COD = CLE.CLE_COD)
     LEFT JOIN PRE ON (SMK.SMK_TIPO = PRE.PRE_SMK_TIPO) AND (SMK.SMK_COD = PRE.PRE_SMK_COD) AND (PRE.PRE_TAB_COD = 'SUS')
   
WHERE RCI_OSM_SERIE=125 AND  
      RCI_OSM_NUM IN (7409,11420) AND
      RCI_SMK_COD <> '04150200' ) X