SELECT OSM.OSM_SERIE,
       OSM.OSM_NUM,
       OSM.OSM_DTHR,
       PAC.PAC_NOME,
       SMK.SMK_NOME,
       PSV.PSV_CRM,
       PSV.PSV_APEL,
       SMM.SMM_VLR AS VLR,
       SUM(EXT.EXT_VALOR_GLOSA),
       SUM(EXT.EXT_VALOR_RECEB),
       CTF.CTF_NOME,
       CNV.CNV_NOME
FROM SMM 
     INNER JOIN OSM ON (OSM.OSM_SERIE = SMM.SMM_OSM_SERIE) AND (OSM.OSM_NUM = SMM.SMM_OSM)
     INNER JOIN PAC ON (PAC.PAC_REG = OSM.OSM_PAC)
     INNER JOIN SMK ON (SMK.SMK_COD = SMM.SMM_COD) AND (SMK.SMK_TIPO = SMM.SMM_TPCOD)
     INNER JOIN CTF ON (SMK.SMK_CTF = CTF.CTF_COD)
     INNER JOIN PSV ON (SMM.SMM_MED = PSV.PSV_COD)
     INNER JOIN CNV ON (CNV.CNV_COD = OSM.OSM_CNV)
     LEFT JOIN EXT ON (EXT.EXT_OSM_SERIE = OSM.OSM_SERIE) AND (EXT.EXT_OSM_NUM = OSM.OSM_NUM) AND (EXT.EXT_SMM_NUM = SMM.SMM_NUM)
WHERE OSM.OSM_DTHR >= :DATA_INICIO AND
      OSM.OSM_DTHR <= :DATA_FIM AND 
      SMM.SMM_EXEC <> 'C' AND
      SMK.SMK_TIPO = 'S' AND 
      CNV.CNV_CAIXA_FATURA = 'F' AND
      (CTF.CTF_COD IN ('4100', '4110') OR CTF.CTF_COD IN (:CLASSE))
GROUP BY OSM.OSM_SERIE,
       	OSM.OSM_NUM,
			SMK.SMK_COD,
			SMK.SMK_NOME,
			CTF.CTF_NOME,
			OSM.OSM_DTHR,
			PAC.PAC_NOME,
			PSV.PSV_CRM,
	      PSV.PSV_APEL,
         SMM.SMM_VLR,
         EXT.EXT_SMM_NUM,
         CNV.CNV_NOME

UNION ALL

SELECT OSM.OSM_SERIE,
       OSM.OSM_NUM,
       OSM.OSM_DTHR,
       PAC.PAC_NOME,
      'CONTRASTE' AS MAT,
       PSV.PSV_CRM,
       PSV.PSV_APEL,
       SUM(SMM.SMM_VLR) AS VLR,
       SUM(EXT.EXT_VALOR_GLOSA),
       SUM(EXT.EXT_VALOR_RECEB),
       CASE 
           WHEN SMM.SMM_STR = '1X' THEN 'CONTRASTE TC'
           WHEN SMM.SMM_STR = '1Y' THEN 'CONTRASTE RM'
           WHEN SMM.SMM_STR = '26' THEN 'CONSTRASTE'
       ELSE SMM.SMM_STR END,
       CNV.CNV_NOME
       
FROM OSM
     INNER JOIN SMM ON (OSM.OSM_SERIE = SMM.SMM_OSM_SERIE) AND (OSM.OSM_NUM = SMM.SMM_OSM)
     INNER JOIN PAC ON (PAC.PAC_REG = OSM.OSM_PAC)
     INNER JOIN PSV ON (SMM.SMM_MED = PSV.PSV_COD)
     FULL OUTER JOIN CNV ON (CNV.CNV_COD = OSM.OSM_CNV)
     LEFT JOIN EXT ON (EXT.EXT_OSM_SERIE = OSM.OSM_SERIE) AND (EXT.EXT_OSM_NUM = OSM.OSM_NUM) AND (EXT.EXT_SMM_NUM = SMM.SMM_NUM)
WHERE OSM.OSM_DTHR >= :DATA_INICIO AND
      OSM.OSM_DTHR <= :DATA_FIM AND 
      SMM.SMM_EXEC <> 'C' AND
      SMM.SMM_TPCOD = 'M' AND
      SMM.SMM_COD <> 'FLM' AND
      EXISTS (SELECT 1 FROM SMM A INNER JOIN SMK ON (SMK.SMK_COD = A.SMM_COD) AND (SMK.SMK_TIPO = A.SMM_TPCOD) INNER JOIN CTF ON (SMK.SMK_CTF = CTF.CTF_COD) WHERE CTF.CTF_COD IN ('4100','4110') AND A.SMM_OSM_SERIE = OSM.OSM_SERIE AND A.SMM_OSM = OSM.OSM_NUM)
GROUP BY
       OSM.OSM_SERIE,
       OSM.OSM_NUM,
       OSM.OSM_DTHR,
       PAC.PAC_NOME,
       PSV.PSV_CRM,
       PSV.PSV_APEL,
       SMM.SMM_STR,
       CNV.CNV_NOME