SELECT USR.USR_LOGIN, 
       USR.USR_NOME,
       ROUND((CASE WHEN DATEDIFF(MINUTE, RGP.RGP_DTHR_ENTRADA1, RGP.RGP_DTHR_SAIDA1) IS NULL THEN 0 ELSE DATEDIFF(MINUTE, RGP.RGP_DTHR_ENTRADA1, RGP.RGP_DTHR_SAIDA1) END + CASE WHEN DATEDIFF(MINUTE, RGP.RGP_DTHR_ENTRADA2, RGP.RGP_DTHR_SAIDA2) IS NULL THEN 0 ELSE DATEDIFF(MINUTE, RGP.RGP_DTHR_ENTRADA2, RGP.RGP_DTHR_SAIDA2) END ) / 60.0, 2) AS saldo,
       RGP.RGP_DTHR_ENTRADA1 AS ENTRADA1, 
       RGP.RGP_DTHR_SAIDA1 AS SAIDA1,
       RGP.RGP_DTHR_ENTRADA2 AS ENTRADA2, 
       RGP.RGP_DTHR_SAIDA2 AS SAIDA2,
       USR.USR_MATRIC_RH as CargaHoraria
FROM RGP 
INNER JOIN USR ON (RGP.RGP_USR_LOGIN = USR.USR_LOGIN)
WHERE RGP.RGP_DTHR_ENTRADA1 BETWEEN  '2024-09-01 00:00:00'  AND  '2024-10-01 00:00:00' 