CREATE
OR REPLACE VIEW ORPAG_BRADESCO_TAM AS
SELECT
    DISTINCT MQ.ORPAG_BM_COD_OPER AS V_CODIGO,
    GIH.GIH_PAC_REG AS V_PAC_REG,
    GIH.GIH_HSP_NUM AS V_HSP_NUM,
    GIH.GIH_NUMERO AS V_GUIA,
    MQ.ORPAG_BM_TISS_GUIA AS V_TIPO_GUIA
FROM
    GIH
    INNER JOIN SMM ON SMM.SMM_PAC_REG = GIH.GIH_PAC_REG
    AND SMM.SMM_HSP_NUM = GIH.GIH_HSP_NUM
    INNER JOIN OSM ON OSM.OSM_SERIE = SMM.SMM_OSM_SERIE
    AND OSM.OSM_NUM = SMM.SMM_OSM
    INNER JOIN SMK ON SMK.SMK_TIPO = SMM.SMM_TPCOD
    AND SMK.SMK_COD = SMM.SMM_COD
    INNER JOIN CTF ON CTF.CTF_TIPO = SMK.SMK_TIPO
    AND CTF.CTF_COD = SMK.SMK_CTF
    INNER JOIN ORPAG_BRADESCO_MQ MQ ON MQ.ORPAG_BM_CNV_COD = OSM.OSM_CNV
    AND MQ.ORPAG_BM_STR_SOLIC = OSM.OSM_STR
    AND MQ.ORPAG_BM_CTF_TIPO = CTF.CTF_TIPO
    AND MQ.ORPAG_BM_CTF_COD IN (CTF.CTF_COD, CTF.CTF_CTF_COD);