CREATE TABLE "SMART"."ORPAG_BRADESCO_MQ" (
    "ORPAG_BM_CNV_COD" VARCHAR2(3 BYTE) NOT NULL ENABLE,
    "ORPAG_BM_STR_SOLIC" VARCHAR2(3 BYTE) NOT NULL ENABLE,
    "ORPAG_BM_CTF_TIPO" VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "ORPAG_BM_CTF_COD" VARCHAR2(5 BYTE) NOT NULL ENABLE,
    "ORPAG_BM_SMK_COD" VARCHAR2(8 BYTE) NOT NULL ENABLE,
    "ORPAG_BM_TISS_GUIA" VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "ORPAG_BM_COD_OPER" VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "ORPAG_BM_EMP_COD" NUMBER(*, 0),
    "ORPAG_BM_EMP_COD_SOLIC" NUMBER(*, 0),
    CONSTRAINT "ORPAG_BRADESCO_MQ_PK" PRIMARY KEY (
        "ORPAG_BM_CNV_COD",
        "ORPAG_BM_STR_SOLIC",
        "ORPAG_BM_CTF_TIPO",
        "ORPAG_BM_CTF_COD",
        "ORPAG_BM_SMK_COD",
        "ORPAG_BM_TISS_GUIA"
    ) USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
        INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    ) TABLESPACE "SMART_DAD" ENABLE
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "SMART_DAD";

GRANT DELETE ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTPROD";

GRANT INDEX ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTPROD";

GRANT
INSERT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTPROD";

GRANT
SELECT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTPROD";

GRANT
UPDATE
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTPROD";

GRANT REFERENCES ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTPROD";

GRANT ON COMMIT REFRESH ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTPROD";

GRANT QUERY REWRITE ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTPROD";

GRANT DEBUG ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTPROD";

GRANT FLASHBACK ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTPROD";

GRANT DELETE ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTUSER";

GRANT
INSERT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTUSER";

GRANT
SELECT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTUSER";

GRANT
UPDATE
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTUSER";

GRANT
SELECT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTSELECT";

GRANT
SELECT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTBI";

GRANT
SELECT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "INTEGRACAO" WITH GRANT OPTION;

GRANT DELETE ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTCP200";

GRANT INDEX ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTCP200";

GRANT
INSERT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTCP200";

GRANT
SELECT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTCP200";

GRANT
UPDATE
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTCP200";

GRANT REFERENCES ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTCP200";

GRANT ON COMMIT REFRESH ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTCP200";

GRANT QUERY REWRITE ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTCP200";

GRANT DEBUG ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTCP200";

GRANT FLASHBACK ON "SMART"."ORPAG_BRADESCO_MQ" TO "SMARTCP200";

GRANT DELETE ON "SMART"."ORPAG_BRADESCO_MQ" TO "INTEGRACAO";

GRANT
INSERT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "INTEGRACAO";

GRANT
UPDATE
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "INTEGRACAO";

GRANT DELETE ON "SMART"."ORPAG_BRADESCO_MQ" TO "TREASY";

GRANT
INSERT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "TREASY";

GRANT
SELECT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "TREASY";

GRANT
UPDATE
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "TREASY";

GRANT DELETE ON "SMART"."ORPAG_BRADESCO_MQ" TO "INGENIUM";

GRANT
INSERT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "INGENIUM";

GRANT
SELECT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "INGENIUM";

GRANT
UPDATE
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "INGENIUM";

GRANT
SELECT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "PIXEON";

GRANT
SELECT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "R_CUBO_SMART";

GRANT DELETE ON "SMART"."ORPAG_BRADESCO_MQ" TO "CUBO";

GRANT
INSERT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "CUBO";

GRANT
SELECT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "CUBO";

GRANT
UPDATE
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "CUBO";

GRANT
SELECT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "RL_TABLES_SMART";

GRANT
SELECT
    ON "SMART"."ORPAG_BRADESCO_MQ" TO "FALQONQLIK";