WITH COMPETENCIA AS (
    SELECT CONVERT(VARCHAR, OSM.OSM_DTHR, 103) AS DIA
FROM OSM
 WITH (NOLOCK) WHERE  OSM.OSM_DTHR >=  '2-1-2025 0:0:0.000' AND
      OSM.OSM_DTHR <  '2-2-2025 0:0:0.000' 
GROUP BY CONVERT(VARCHAR, OSM.OSM_DTHR, 103)
),
PROCEDENCIA AS (
    SELECT CASE 
            WHEN STR.STR_NOME LIKE '%ENF.C.M%' THEN 'CLINICA MEDICA'  
            WHEN STR.STR_NOME LIKE '%ENF. C.M%' THEN 'CLINICA MEDICA'  
            WHEN STR.STR_NOME LIKE '%ENF.CIR. GERAL%' THEN 'CIRURGIA GERAL'
            WHEN STR.STR_NOME LIKE '%BERCARIO ALA VERDE%' THEN 'PEDIATRIA'
            WHEN STR.STR_NOME LIKE '%ENF.ORTO%' THEN 'ORTOPEDIA'
            WHEN STR.STR_NOME LIKE '%EDIATRICA%' THEN 'PEDIATRIA'
            WHEN STR.STR_NOME LIKE '%ISOLAMENTO%' THEN 'CLINICA MEDICA'
            WHEN STR.STR_NOME LIKE '%OBSERVACAO%' THEN 'OBSERVAÇÃO'
            WHEN STR.STR_NOME LIKE '%UTI%' THEN 'UTI'
            WHEN STR.STR_NOME LIKE '%SALA VERMELHA%' THEN 'SALA VERMELHA'
            ELSE 'NÃO ESPECIFICADO'
        END AS CATEGORIA,
        STR.STR_COD AS COD
    FROM STR
)

SELECT COMPETENCIA.DIA,
       PROCEDENCIA.CATEGORIA,
       COUNT(LOC.LOC_COD) AS LEITO,
       (SELECT COUNT(*) FROM HSP WHERE (HSP.HSP_DTHRE <= COMPETENCIA.DIA) AND (HSP.HSP_DTHRA >= COMPETENCIA.DIA OR HSP.HSP_DTHRA IS NULL) AND  (HSP.HSP_TRAT_INT = 'I')) AS INTERNADOS
FROM COMPETENCIA
     CROSS JOIN PROCEDENCIA
     INNER JOIN STR ON (STR.STR_COD = PROCEDENCIA.COD)
     INNER JOIN LOC ON (STR.STR_COD = LOC.LOC_STR)
GROUP BY COMPETENCIA.DIA,
         PROCEDENCIA.CATEGORIA
 ORDER BY COMPETENCIA.DIA, 
         PROCEDENCIA.CATEGORIA
(SELECT COUNT(*) FROM HSP WHERE (HSP.HSP_DTHRE <= COMPETENCIA.DIA) AND (HSP.HSP_DTHRA >= COMPETENCIA.DIA OR HSP.HSP_DTHRA IS NULL) AND  (HSP.HSP_TRAT_INT = 'I')) AS INTERNADOS