-- Criando um backup da tabela antes de modificar
CREATE TABLE SMART.ORPAG_BRADESCO_MQ_BKP AS SELECT * FROM SMART.ORPAG_BRADESCO_MQ;

-- Agora você pode modificar a tabela original
ALTER TABLE SMART.ORPAG_BRADESCO_MQ MODIFY ORPAG_BM_CNV_COD VARCHAR2(5 BYTE);
ALTER TABLE SMART.ORPAG_BRADESCO_MQ MODIFY ORPAG_BM_STR_SOLIC VARCHAR2(5 BYTE);
ALTER TABLE SMART.ORPAG_BRADESCO_MQ MODIFY ORPAG_BM_CTF_TIPO VARCHAR2(2 BYTE);
ALTER TABLE SMART.ORPAG_BRADESCO_MQ MODIFY ORPAG_BM_CTF_COD VARCHAR2(6 BYTE);
ALTER TABLE SMART.ORPAG_BRADESCO_MQ MODIFY ORPAG_BM_SMK_COD VARCHAR2(10 BYTE);
ALTER TABLE SMART.ORPAG_BRADESCO_MQ MODIFY ORPAG_BM_TISS_GUIA VARCHAR2(12 BYTE);
ALTER TABLE SMART.ORPAG_BRADESCO_MQ MODIFY ORPAG_BM_COD_OPER VARCHAR2(40 BYTE);
ALTER TABLE SMART.ORPAG_BRADESCO_MQ MODIFY ORPAG_BM_EMP_COD NUMBER(10, 0);
ALTER TABLE SMART.ORPAG_BRADESCO_MQ MODIFY ORPAG_BM_EMP_COD_SOLIC NUMBER(10, 0);

-- (ROLLBACK) Se precisar reverter, apague a tabela alterada e recupere a original
DROP TABLE SMART.ORPAG_BRADESCO_MQ;
CREATE TABLE SMART.ORPAG_BRADESCO_MQ AS SELECT * FROM SMART.ORPAG_BRADESCO_MQ_BKP;
